@{
    # Module manifest for Tiny11 Builder - Ultimate Edition : GUI module.
    # GENERATED by scripts\update-generated.ps1 - FunctionsToExport mirrors the module.
    RootModule           = 'tiny11gui.psm1'
    ModuleVersion        = '2026.9.0'
    GUID                 = 'b8a12345-1234-5678-9abc-def012345678'
    Author               = 'Tiny11 Builder Ultimate Edition contributors'
    CompanyName          = 'Tiny11 Builder'
    Description          = 'Windows Forms builder window for Tiny11 Builder - Ultimate Edition (every option, live build log).'
    PowerShellVersion    = '5.1'
    CompatiblePSEditions = @('Desktop')
    RequiredModules      = @()
    FunctionsToExport    = @(
        'ConvertTo-GuiBuildRequest',
        'Export-GuiSettings',
        'Format-GuiCommandLine',
        'Format-GuiEdition',
        'Get-GuiBuildStage',
        'Get-GuiCompressionDescription',
        'Get-GuiDefaultState',
        'Get-GuiFlagInfo',
        'Get-GuiLineKind',
        'Get-GuiPresetDescription',
        'Get-GuiTweakRows',
        'Get-NtfsDrives',
        'Get-SetupMediaDrives',
        'Get-SourceEditions',
        'Import-GuiSettings',
        'Invoke-PopupError',
        'Invoke-PopupInfo',
        'Invoke-PopupYesOrNo',
        'New-UiControl',
        'Read-GuiLogTail',
        'Set-GuiTweakChoice',
        'Show-Tiny11BuilderForm',
        'Start-GuiBuild',
        'Stop-GuiBuild',
        'Test-GuiBuildRequest',
        'Test-GuiFlagsModified',
        'Test-GuiRemoveListModified'
    )
    CmdletsToExport      = @()
    VariablesToExport    = @()
    AliasesToExport      = @()
    PrivateData          = @{
        PSData = @{
            Tags       = @('tiny11', 'windows11', 'debloat', 'gui')
            ProjectUri = 'https://github.com/NairoDorian/tiny11builder_2026'
        }
    }
}
