@{
    # Module manifest for Tiny11 Builder - Ultimate Edition : shared build library.
    # GENERATED by scripts\update-generated.ps1 - FunctionsToExport mirrors the module.
    RootModule           = 'tiny11utils.psm1'
    ModuleVersion        = '2026.9.0'
    GUID                 = 'a1b2c3d4-1234-5678-9abc-def012345678'
    Author               = 'Tiny11 Builder Ultimate Edition contributors'
    CompanyName          = 'Tiny11 Builder'
    Description          = 'Offline Windows image servicing for Tiny11 Builder: DISM/registry helpers, tweak catalog, answer files, removal planning and ISO creation.'
    PowerShellVersion    = '5.1'
    CompatiblePSEditions = @('Desktop')
    FunctionsToExport    = @(
        'Add-BuildDefenderExclusion',
        'Add-DeprovisionedPackage',
        'Add-ImageDrivers',
        'Assert-CommandExitCode',
        'Assert-MountedImage',
        'Assert-OfflineHiveLoaded',
        'Assert-WindowsSourceDrive',
        'Assert-WinSxSRebuild',
        'Build-ProcessArgumentString',
        'Clear-FileReadOnly',
        'Clear-StaleBuildState',
        'ConvertFrom-PresetJson',
        'ConvertFrom-TweakEntry',
        'ConvertTo-ArchitectureName',
        'ConvertTo-PresetJson',
        'ConvertTo-UnattendPassword',
        'Dismount-OfflineHives',
        'Dismount-WindowsSource',
        'Enable-Privilege',
        'Enable-TaskCacheWriteAccess',
        'Export-FinalInstallImage',
        'Find-Oscdimg',
        'Format-BuildSummary',
        'Format-Elapsed',
        'Format-ProcessArgument',
        'Get-AvailableImageIndex',
        'Get-BootWimIndex',
        'Get-CapabilitiesToRemove',
        'Get-CoreWindowsPackagesToRemove',
        'Get-ImageInfo',
        'Get-MaxParallelJobs',
        'Get-OfflineTaskIds',
        'Get-OptionalUtilities',
        'Get-OscdimgBootArgument',
        'Get-PackageFamilyName',
        'Get-PresetFlagNames',
        'Get-PresetFlagSection',
        'Get-ProtectedAppxPrefixes',
        'Get-RequiredScratchBytes',
        'Get-Sha256',
        'Get-TelemetryScheduledTasks',
        'Get-Tiny11PayloadFiles',
        'Get-TweakCatalog',
        'Get-TweakPlan',
        'Get-WindowsDisplayVersion',
        'Grant-AdminFullControl',
        'Initialize-Oscdimg',
        'Initialize-ScratchWorkspace',
        'Install-ImagePayload',
        'Invoke-AppRemovalStage',
        'Invoke-BootImageStage',
        'Invoke-CapabilityRemovalStage',
        'Invoke-ComponentCleanup',
        'Invoke-DismChecked',
        'Invoke-EmergencyCleanup',
        'Invoke-Native',
        'Invoke-RegistryStage',
        'Invoke-RegLoad',
        'Invoke-RegUnload',
        'Invoke-Robocopy',
        'Invoke-SafeDismountImage',
        'Invoke-SafeOfflineRegistryUnload',
        'Invoke-TweakCatalog',
        'Invoke-TweakGroup',
        'Mount-IsoAndGetDriveLetter',
        'Mount-OfflineHives',
        'New-FirstLogonScript',
        'New-SetupCompleteScript',
        'New-Tiny11Iso',
        'New-UnattendXml',
        'Read-PackageListFile',
        'Read-PowerShellDataFile',
        'Remove-BuildDefenderExclusion',
        'Remove-EdgeFiles',
        'Remove-ImagePath',
        'Remove-OfflineScheduledTask',
        'Remove-OneDriveFiles',
        'Remove-RegistryValue',
        'Resolve-AppxRemovalList',
        'Resolve-Architecture',
        'Resolve-BuildPreset',
        'Resolve-BuildProfile',
        'Resolve-OptionalUtilities',
        'Resolve-WindowsSource',
        'Select-ImageIndex',
        'Set-OfflineServiceStart',
        'Set-RegistryValue',
        'Set-UnattendImageIndex',
        'Show-PackageSelector',
        'Show-WindowsImageMenu',
        'Test-AppxPrefixMatch',
        'Test-IsoResult',
        'Test-OfflineRegistryPath',
        'Test-Prerequisites',
        'Test-RobocopySucceeded',
        'Test-ScratchDiskNtfs',
        'Test-SufficientScratch',
        'Test-TweakCondition',
        'Write-BuildManifest',
        'Write-UnattendFile'
    )
    CmdletsToExport      = @()
    VariablesToExport    = @()
    AliasesToExport      = @()
    PrivateData          = @{
        PSData = @{
            Tags       = @('tiny11', 'windows11', 'debloat', 'dism', 'unattend')
            ProjectUri = 'https://github.com/NairoDorian/tiny11builder_2026'
        }
    }
}
