#requires -Version 5.1
<#
.SYNOPSIS
    Regenerates the files derived from code: docs\TWEAKS.md (from
    data\tweaks.psd1 + presets) and the reference answer files
    autounattend.xml / autounattend-arm64.xml (from New-UnattendXml).

.DESCRIPTION
    Run after editing the tweak catalog, a preset or the answer-file
    generator. CI runs it with -Check and fails when a generated file is out
    of date, so documentation can never drift from what the builders do.

.PARAMETER Check
    Do not write anything; exit 1 if any generated file differs.
#>
param([switch]$Check)

$ErrorActionPreference = 'Stop'
$repo = Split-Path -Parent $PSScriptRoot
Import-Module -Name (Join-Path $repo 'lib\tiny11utils.psm1') -Force -DisableNameChecking

$outputs = [ordered]@{}

#---------[ docs\TWEAKS.md ]---------#
$catalog = Get-TweakCatalog
$presets = 'Default', 'Gaming', 'PrivacyPlus', 'Minimal-VM'
$planByPreset = @{}
foreach ($p in $presets) { $planByPreset[$p] = @(Get-TweakPlan -Flags (Resolve-BuildPreset $p) | ForEach-Object { $_.Id }) }
$coreFlags = (Resolve-BuildPreset 'Minimal-VM').Clone()
foreach ($k in 'RemoveEdge', 'RemoveWebView', 'RemoveOneDrive', 'RemoveDefender', 'DisableWindowsUpdate') { $coreFlags[$k] = $true }
$coreFlags['TuneDefenderCpuLimit'] = $false
$planByPreset['Core'] = @(Get-TweakPlan -Flags $coreFlags | ForEach-Object { $_.Id })
$columns = $presets + 'Core'

$md = New-Object System.Collections.Generic.List[string]
$md.Add('# Registry tweak catalog')
$md.Add('')
$md.Add('<!-- GENERATED by scripts/update-generated.ps1 from data/tweaks.psd1 - do not edit by hand. -->')
$md.Add('')
$md.Add('Every registry change the builders make to the installed image, grouped as in')
$md.Add('[`data/tweaks.psd1`](../data/tweaks.psd1). Hives are the offline copies of the image:')
$md.Add('`zSOFTWARE`/`zSYSTEM` = `HKLM\SOFTWARE`/`HKLM\SYSTEM`, `zNTUSER` = the Default user')
$md.Add('profile (inherited by every new account), `zDEFAULT` = the `.DEFAULT` profile.')
$md.Add('')
$md.Add('Leave groups out with `-SkipTweak Id1,Id2`. The `When` column names the preset flag')
$md.Add('(see [`presets/`](../presets)) or builder switch that enables a group.')
$md.Add('')
$md.Add('## Which groups each preset applies')
$md.Add('')
$md.Add('| Group | When | ' + ($columns -join ' | ') + ' |')
$md.Add('|---|---|' + (($columns | ForEach-Object { ':---:' }) -join '|') + '|')
foreach ($g in $catalog) {
    $cells = $columns | ForEach-Object { if ($planByPreset[$_] -contains $g.Id) { 'x' } else { '' } }
    $md.Add("| [$($g.Id)](#$($g.Id.ToLowerInvariant())) | ``$($g.When)`` | " + ($cells -join ' | ') + ' |')
}
$md.Add('')
$md.Add('`LowRam` and `DriverUpdates` are switched on by `-LowRam` / `-DisableDriverUpdates`; `WindowsUpdateOff` is Core-only.')
$md.Add('')
foreach ($g in $catalog) {
    $md.Add("## $($g.Id)")
    $md.Add('')
    $md.Add("$($g.Title).")
    $md.Add('')
    $md.Add("- **When:** ``$($g.When)``")
    if ($g.Notes) { $md.Add("- **Note:** $($g.Notes)") }
    $md.Add('')
    $sets = @($g.Set | Where-Object { $_ })
    if ($sets.Count) {
        $md.Add('| Key | Value | Type | Data |')
        $md.Add('|---|---|---|---|')
        foreach ($e in $sets) {
            $t = ConvertFrom-TweakEntry $e
            $name = if ($t.Name) { $t.Name } else { '(default)' }
            $data = $t.Value -replace '\|', '\|'
            $md.Add("| ``$($t.Path)`` | ``$name`` | $($t.Type) | ``$data`` |")
        }
        $md.Add('')
    }
    $deletes = @($g.Delete | Where-Object { $_ })
    if ($deletes.Count) {
        $md.Add('Deleted:')
        $md.Add('')
        foreach ($e in $deletes) {
            $parts = $e -split '\|', 2
            if ($parts.Count -eq 2) { $md.Add("- value ``$($parts[1])`` in ``$($parts[0])``") } else { $md.Add("- key ``$e``") }
        }
        $md.Add('')
    }
    $services = @($g.Services | Where-Object { $_ })
    if ($services.Count) {
        $md.Add('Services (start type: 2 automatic, 3 manual, 4 disabled; skipped if absent):')
        $md.Add('')
        foreach ($s in $services) { $n, $v = $s -split '=', 2; $md.Add("- ``$n`` -> $v") }
        $md.Add('')
    }
    $firstBoot = @($g.FirstBoot | Where-Object { $_ })
    if ($firstBoot.Count) {
        $md.Add('Runs once at first boot (SetupComplete.cmd, as SYSTEM):')
        $md.Add('')
        $md.Add('```bat')
        foreach ($f in $firstBoot) { $md.Add($f) }
        $md.Add('```')
        $md.Add('')
    }
}
$md.Add('## Scheduled tasks removed (`DisableTelemetry`)')
$md.Add('')
$md.Add('The task definition, its `TaskCache\Tree` key and every `TaskCache` entry for its GUID')
$md.Add('are deleted. The GUID is read from the image, so this works on every build.')
$md.Add('')
foreach ($t in Get-TelemetryScheduledTasks) { $md.Add("- ``$t``") }
$md.Add('')
$outputs['docs\TWEAKS.md'] = ($md -join "`r`n") + "`r`n"

#---------[ Reference answer files ]---------#
$header = @(
    '<!--'
    '    Reference answer file - GENERATED by scripts/update-generated.ps1 (New-UnattendXml).'
    '    The builders generate their own copy for every ISO from your -User / -Password /'
    '    -TimeZone / -Locale / -ComputerName / -ZeroTouch / -InteractiveOobe options.'
    '    This file is only for applying tiny11''s OOBE behaviour to other media by hand:'
    '    local administrator "User" with an empty password, Microsoft-account and network'
    '    pages skipped, hardware checks bypassed, region/keyboard still asked in OOBE.'
    '-->'
) -join "`r`n"
foreach ($arch in 'amd64', 'arm64') {
    $xml = New-UnattendXml -Architecture $arch -UserName 'User'
    $xml = $xml -replace '(?m)^<!-- Generated by Tiny11 Builder Ultimate Edition \(New-UnattendXml\)\. -->\r?\n', ($header + "`r`n")
    $file = if ($arch -eq 'amd64') { 'autounattend.xml' } else { 'autounattend-arm64.xml' }
    $outputs[$file] = $xml
}

#---------[ docs\APPS.md ]---------#
$apps = New-Object System.Collections.Generic.List[string]
$apps.Add('# Apps: removed, optional and protected')
$apps.Add('')
$apps.Add('<!-- GENERATED by scripts/update-generated.ps1 - do not edit by hand. -->')
$apps.Add('')
$apps.Add('Provisioned (Store) apps are matched by **name prefix** against what the image actually')
$apps.Add('contains, so entries for apps a given build does not ship are simply ignored. Removed apps')
$apps.Add('are also marked *deprovisioned*, so feature updates do not reinstall them.')
$apps.Add('')
$apps.Add('## Removed by default ([`removePackage.txt`](../removePackage.txt))')
$apps.Add('')
$section = $null
foreach ($line in (Get-Content (Join-Path $repo 'removePackage.txt'))) {
    if ($line -match '^# --- (.+?) -+\s*$') {
        if ($section) { $apps.Add('') }
        $section = $Matches[1]
        $apps.Add("**$section**")
        $apps.Add('')
        continue
    }
    $entry = ($line -replace '#.*$', '').Trim()
    if ($entry -and $section) { $apps.Add("- ``$entry``") }
}
$apps.Add('')
$apps.Add('Use your own list with `-PackageList my-list.txt`, or pick interactively with `-Custom`.')
$apps.Add('')
$apps.Add('## Optional utilities (`-Keep` / `-Remove`)')
$apps.Add('')
$apps.Add('| Name | Package prefix(es) | Default |')
$apps.Add('|---|---|---|')
foreach ($u in Get-OptionalUtilities) {
    $prefixes = (@($u.Prefixes) | ForEach-Object { '`' + $_ + '`' }) -join ', '
    $apps.Add("| $($u.Name) | $prefixes | $($u.Default) |")
}
$apps.Add('')
$apps.Add('Example: `-Keep Paint,SnippingTool -Remove Terminal`.')
$apps.Add('')
$apps.Add('## Never removed (protected)')
$apps.Add('')
$apps.Add('Frameworks other apps depend on, `winget` and media codecs are protected even if a list')
$apps.Add('entry would match them:')
$apps.Add('')
foreach ($p in Get-ProtectedAppxPrefixes -AllowStoreRemoval -AllowSecurityUiRemoval) { $apps.Add("- ``$p``") }
$apps.Add('')
$apps.Add('## Preset-dependent')
$apps.Add('')
$apps.Add('| App | Default | Gaming | PrivacyPlus | Minimal-VM / Core |')
$apps.Add('|---|---|---|---|---|')
$apps.Add('| Microsoft Store (`Microsoft.WindowsStore`, `Microsoft.StorePurchaseApp`) | kept | kept | kept | removed |')
$apps.Add('| Windows Security app (`Microsoft.SecHealthUI`) | kept | kept | kept | removed |')
$apps.Add('| Xbox app, Game Bar, Xbox sign-in | removed | **kept** | removed | removed |')
$apps.Add('| Edge browser | removed | removed | removed | removed |')
$apps.Add('| Edge WebView2 runtime | kept | kept | kept | removed |')
$apps.Add('| OneDrive | removed | removed | removed | removed |')
$apps.Add('')
$apps.Add('## Windows capabilities')
$apps.Add('')
$apps.Add('Standard builds remove Internet Explorer mode, Math Input Panel, WordPad, Steps Recorder,')
$apps.Add('PowerShell ISE, Quick Assist, the XPS Viewer, extended wallpapers, and the handwriting and speech')
$apps.Add('packs of the image language. OCR, text-to-speech (Narrator) and the basic language features')
$apps.Add('(spell-check, typing) are kept. Core builds also remove OCR, text-to-speech and legacy Windows')
$apps.Add('Media Player, plus the matching component packages and Defender.')
$apps.Add('')
$outputs['docs\APPS.md'] = ($apps -join "`r`n") + "`r`n"

#---------[ lib\tiny11utils.psd1 (FunctionsToExport) ]---------#
$functionNames = @(Get-Command -Module tiny11utils | ForEach-Object { $_.Name } | Sort-Object)
$exportList = ($functionNames | ForEach-Object { "        '$_'" }) -join ",`r`n"
$outputs['lib\tiny11utils.psd1'] = @"
@{
    # Module manifest for Tiny11 Builder - Ultimate Edition : shared build library.
    # GENERATED by scripts\update-generated.ps1 - FunctionsToExport mirrors the module.
    RootModule           = 'tiny11utils.psm1'
    ModuleVersion        = '2026.9.0'
    GUID                 = 'a1b2c3d4-1234-5678-9abc-def012345678'
    Author               = 'Tiny11 Builder Ultimate Edition contributors'
    CompanyName          = 'Tiny11 Builder'
    Description          = 'Offline Windows image servicing for Tiny11 Builder: DISM/registry helpers, tweak catalog, answer files, removal planning and ISO creation.'
    PowerShellVersion    = '5.1'
    CompatiblePSEditions = @('Desktop')
    FunctionsToExport    = @(
$exportList
    )
    CmdletsToExport      = @()
    VariablesToExport    = @()
    AliasesToExport      = @()
    PrivateData          = @{
        PSData = @{
            Tags       = @('tiny11', 'windows11', 'debloat', 'dism', 'unattend')
            ProjectUri = 'https://github.com/NairoDorian/tiny11builder_2026'
        }
    }
}

"@ -replace "`r?`n", "`r`n"

#---------[ lib\tiny11gui.psd1 (FunctionsToExport) ]---------#
Import-Module -Name (Join-Path $repo 'lib\tiny11gui.psm1') -Force -DisableNameChecking
$guiNames = @(Get-Command -Module tiny11gui | ForEach-Object { $_.Name } | Sort-Object)
$guiList = ($guiNames | ForEach-Object { "        '$_'" }) -join ",`r`n"
$outputs['lib\tiny11gui.psd1'] = @"
@{
    # Module manifest for Tiny11 Builder - Ultimate Edition : GUI module.
    # GENERATED by scripts\update-generated.ps1 - FunctionsToExport mirrors the module.
    RootModule           = 'tiny11gui.psm1'
    ModuleVersion        = '2026.9.0'
    GUID                 = 'b8a12345-1234-5678-9abc-def012345678'
    Author               = 'Tiny11 Builder Ultimate Edition contributors'
    CompanyName          = 'Tiny11 Builder'
    Description          = 'Windows Forms builder window for Tiny11 Builder - Ultimate Edition (every option, live build log).'
    PowerShellVersion    = '5.1'
    CompatiblePSEditions = @('Desktop')
    RequiredModules      = @()
    FunctionsToExport    = @(
$guiList
    )
    CmdletsToExport      = @()
    VariablesToExport    = @()
    AliasesToExport      = @()
    PrivateData          = @{
        PSData = @{
            Tags       = @('tiny11', 'windows11', 'debloat', 'gui')
            ProjectUri = 'https://github.com/NairoDorian/tiny11builder_2026'
        }
    }
}

"@ -replace "`r?`n", "`r`n"

#---------[ Write or check ]---------#
$stale = @()
$utf8 = New-Object System.Text.UTF8Encoding $false
foreach ($entry in $outputs.GetEnumerator()) {
    $path = Join-Path $repo $entry.Key
    $current = if (Test-Path $path) { [IO.File]::ReadAllText($path) } else { $null }
    $normalize = { param($s) if ($null -eq $s) { '' } else { $s -replace "`r`n", "`n" } }
    if ((& $normalize $current) -ne (& $normalize $entry.Value)) {
        $stale += $entry.Key
        if (-not $Check) {
            $encoding = if ($path -match '\.ps(m|d)?1$') { New-Object System.Text.UTF8Encoding $true } else { $utf8 }
            [IO.File]::WriteAllText($path, $entry.Value, $encoding)
            Write-Host "updated $($entry.Key)"
        }
    }
}
if ($Check) {
    if ($stale.Count) {
        Write-Host "Out of date (run scripts\update-generated.ps1): $($stale -join ', ')" -ForegroundColor Red
        exit 1
    }
    Write-Host 'Generated files are up to date.'
} elseif (-not $stale.Count) {
    Write-Host 'Nothing to update.'
}
exit 0
